version: "3"
services:
    viewer:
        image: semmtech/linked-data-viewer:3.5.3
        restart: always
        ports:
            - "8082:8082"
        volumes:
            - ./viewer/server/config.json:/usr/src/app/server/dist/config.json
            - ./viewer/client/config.json:/usr/src/app/client/dist/html/config.json
            - ./viewer/client/queries/:/usr/src/app/client/dist/html/queries/
            - ./viewer/client/static/app-logo.svg:/usr/src/app/client/dist/html/static/images/app-logo.svg
            - ./viewer/client/static/favicon.png:/usr/src/app/client/dist/html/static/favicon.png
