PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX nen2660: <https://w3id.org/nen2660/def#>
PREFIX sh: <http://www.w3.org/ns/shacl#>


SELECT DISTINCT ?group_text ?group_iri ?entry_text ?entry_iri ?entry_badge ?entry_icon
WHERE {

#########################
# This query returns the 'Relations' (as defined in the BPL) for a given concept.
#
# INPUT:
#   ?term_iri: The IRI of the concept
#########################

    ?shape      sh:targetClass      ?term_iri .
    ?shape      sh:property         ?property .   
    ?property   sh:path             ?path  .
    ?property   sh:qualifiedValueShape ?qualifiedValueShape .
    ?qualifiedValueShape    sh:class    ?targetClass .

    OPTIONAL{   ?property       sh:maxCount     ?maxCount } .
    OPTIONAL{   ?property       sh:minCount     ?minCount } .
    OPTIONAL{   ?property       sh:qualifiedMaxCount     ?qmaxCount } .
    OPTIONAL{   ?property       sh:qualifiedMinCount     ?qminCount } .
    OPTIONAL{   ?targetClass    skos:prefLabel  ?targetClassLabel} .
    OPTIONAL{   ?object         skos:prefLabel  ?objectLabel }.
    
    BIND (CONCAT(IF(BOUND(?minCount),STR(?minCount),"0"),":",IF(BOUND(?maxCount),STR(?maxCount),"n")) AS ?entry_badge) .

    BIND(IF(STR(?path) = "https://w3id.org/nen2660/def#isDescribedBy", "isDescribedBy", ?path) AS ?pathLabel)
    BIND (?pathLabel AS ?group_text) 
    BIND (?path AS ?group_iri) 
    BIND (?targetClassLabel AS ?entry_text) 
    BIND (?targetClass AS ?entry_iri) 

    BIND ("icon-term-type-lacestype" AS ?entry_icon) .
   
}
ORDER BY ?group_text ?group_iri ?entry_text ?entry_iri
